apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kemgou-eksctl-cluster-1.22
  region: us-east-2
  version: "1.22"
managedNodeGroups:
- name: primary-1-22
  instanceType: t2.medium
  minSize: 2
  maxSize: 6
  spot: true
